development:
  clients:
    default:.
      database: mongospeedway_development
      hosts:
        - localhost:27017
      options:
       
  options:
   
test:
  clients:
    default:
      database: mongospeedway_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
        
production:
  clients:
    default:
      database: mongodb://heroku_1tw2lm9q:gbjfetp45k759m54v0bmpm1h0c@ds119652.mlab.com:19652/heroku_1tw2lm9q
      options:
        skip_version_check: true

